### ISSUE TITLE
response content type

### ISSUE THREAD

**Issue by jnhmcknight** [scoates/paste.website#1]
You're setting the `content_type` on [lines 49-52](https://github.com/scoates/paste.website/blob/41def1ead50cf2575fc0bcb064c3590cceb46733/app.py#L49-L52), but then explicitly set the response `mimetype` to `text/plain` on [line 63](https://github.com/scoates/paste.website/blob/41def1ead50cf2575fc0bcb064c3590cceb46733/app.py#L63).

```
def fetch(filename):
    if filename.endswith('.txt'):
        content_type = 'text/plain'
    elif filename.endswith('.html'):
        content_type = 'text/html'
    else:
        # other types not allowed
        abort(404)

    s3 = boto3.client('s3')
    try:
        obj = s3.get_object(Bucket=BUCKET, Key=filename)
    except ClientError:
        abort(404)

    return Response(obj['Body'].read(), mimetype='text/plain')
```

Oversight or on purpose?

**Comment by scoates** [comment]
Yep. Accident. HTML is legacy anyway, but this should be `mimetype=content_type`. Nice catch.
